[project]
name = "stock-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "python-dateutil>=2.9.0.post0",
    "streamlit>=1.50.0",
]
